### PR TITLE
Update Add more AMOLED Dark.xml

### PR DESCRIPTION
**Pull request by JohnBetaro**
One of the cool things I like about Molly is the black theme, but I hope you'll accept this change to make it even cooler.

### CODE REVIEW

**Comment by BHydden** [comment]
Why did you close https://github.com/mollyim/mollyim-android/pull/182 ?

**Comment by JohnBetaro** [comment]
Just by mistake

**Comment by valldrac** [comment]
Thanks for the pull-request! Can you add some screenshots so we can see the difference?

**Comment by JohnBetaro** [comment]
As per your request, I hope you like it.

**Comment by p1gp1g** [comment]
It would be nice to have a before after to see the changes. And having the related variable, if we want to keep/ change some.

You can use a table to do this
```
Before | After | Vars
---|---|---
Img1 | Img2 | signal_dark_color

**Comment by p1gp1g** [comment]
I'm OK that PR currently reduces accessibility. That's why I've suggested to use a darker color than current ones but not full black.

I'm also OK that AMOLED black may reduces accessibility. I think the best thing would be having 3 themes : light, dark, black

**Pull request closed without merging**
