### PR TITLE
WIP: nb_NO strings reworked

### PR DESCRIPTION
**Pull request by comradekingu**
The contribution guidelines currently state making contributions means granting a CLA to Signal "control", which I don't want. Also found the source strings to be quite poor, so might start there.
Not sure how many of the "Signal" mentions should be changed for "Molly".
Hope to see it on F-Droid.
Also, registering at https://weblate.org/hosting/ makes it easy for everyone to contribute :)

### CODE REVIEW

**Comment by valldrac** [comment]
Hi. Thanks for your pull-request.

I already had the plan to release Molly on F-Droid in my backlog. So this weekend I have created a repo at https://molly.im/fdroid. You could test it if you want. The APKs are the same signed binaries that are released on GitHub.

Now about the poor translations. I can merge your fixes, but take into account that, sooner or later, they will be overwritten as Signal modifies them. I cannot maintain strings in Norwegian.

Have you tried to contribute to Signal via transifex.com? This way all Signal users would be benefit from your fixes.

**Comment by comradekingu** [comment]
@Valldrac I think they do already, and I stopped contributing ever since Signal slapped a CLA on "their" translations. As I don't use Transifex following their change of terms, or communication software with no functional way of correcting language, guess that means no Signal for me.
Register the project at Hosted Weblate and you won't have to. Not correcting the source strings is a second rate idea.

**Comment by valldrac** [comment]
@comradekingu What's wrong with Signal's CLA?

**Comment by comradekingu** [comment]
@valldrac A lot. I made a thread about it on their forum. Signal is the project that just manages to make issues where none are needed.

**Comment by valldrac** [comment]
@comradekingu Okay, I read it. You set the standard very high.

I have requested free hosting in Weblate. It's a good idea actually. Waiting for approval.

**Comment by valldrac** [comment]
@comradekingu Molly-specific strings are already available in Weblate for translation. For Signal original strings, I've opened a support ticket to add a new component. So the project will have two components. One named "Molly App" for strings2.xml monolingual file, and another named "Upstream" for original strings.xml

I'm afraid some translations have been lost the first day while I was setting up the workflow. When I went for the gratis version, they configured the project for me. And of course they didn't realize Molly is a fork and it has two sources for strings.

**Pull request closed without merging**
