### PR TITLE
Added OLED black theme.

### PR DESCRIPTION
**Pull request by johanw666**
Added OLED black theme.

### CODE REVIEW

**Comment by valldrac** [comment]
Thanks for the PR. I'll review it after the first version is released.

**Comment by Meteor0id** [comment]
It would be nicer if the existing dark theme was modified to be OLED compatible, but of course that might be even more maintenance.

**Comment by nutts0** [comment]
Can u merg this

**Comment by valldrac** [comment]
I chose to replace the current dark theme instead of creating a new theme. It would be a mess to mantain it.

**Pull request closed without merging**
