### PR TITLE
Minor grammar correction in strings2.xml

### PR DESCRIPTION
**Pull request by taivlam**
Minor grammar gerund correction (change "remain" to "remaining" in "Clearing unencrypted data remain in RAM" message)

### CODE REVIEW

**Comment by valldrac** [comment]
Thanks for bringing this up. It's a grammar error indeed.

We discussed this in the Matrix room and they suggested to better replace this string by 'Clearing unencrypted data from RAM". It's shorter and avoid the use of two gerunds in the same phrase.

Would you like to do this modification?

Note that the identifier `WipeMemoryService_clearing_unencrypted_data_remain_in_ram` should be changed accordingly too, both in the XML and in the source code (I think it's only referenced in one Java file). This is needed to sync the translations.

**Comment by taivlam** [comment]
@valldrac Yes, I think the shorter string, "Clearing unencrypted data from RAM" is better.

Initially, I was hesitant to modify the XML identifier because I didn't know how many times I had to replace that everywhere in the repository, since there are quite a few other translations built in Molly.

I'll change the identifier here accordingly (if I can figure how to modify this pull request on GitHub) and I believe I've located the mentioned [Java file](https://github.com/mollyim/mollyim-android/blob/3c61b6c15367ced4fb2a5b66d3cd1467805144cd/app/src/main/java/org/thoughtcrime/securesms/service/WipeMemoryService.java).

**Comment by valldrac** [comment]
Great. Please, do not replace the identifier in the translations. Only in the main language (English) XML file and in the Java code. The Weblate service will take care of fixing the rest of languages.

**Comment by taivlam** [comment]
So I was unable to figure out how to add the commit for the Java file, so it's in #57.
(I really wanted to avoid this, but I've haven't more than simple commits in the browser so far.  At a quick glance from web searching, it seems what I originally wanted to do was most easily via the CLI.)

**Comment by valldrac** [comment]
Hmm what a mess. I have never used the browser for pushing commits. I prefer CLI flexibility.

But no worries. I already squashed and merged the pull-requests to master. Thanks for contributing :pray:

**Pull request closed without merging**
