### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by phoropter**
Add text denoting mollysocket requirement for Molly-UP, unavailability for linked devices, and updated table.

### CODE REVIEW

**Comment by BHydden** [comment]
In line 73 it might be good to directly state whether Molly-UP has blobs or not. The way it is written in your proposal I think leaves it ambiguous.

**Comment by BHydden** [comment]
Yeah sounds good thanks for that.

**Comment by phoropter** [comment]
I think with 3 choices, a bullet list makes readability easier.

**Comment by BHydden** [comment]
I agree. Latest version is very clear ❤️

**Comment by valldrac** [comment]
Thank you for the contribution. I've corrected some errors and made some changes to enhance clarity.

**Pull request merged**
