### PR TITLE
Revert dark background color to upstream value for readability purpose

### PR DESCRIPTION
**Pull request by BayLee4**
Linked to issue #128, helps with strained eyes

### CODE REVIEW

**Comment by BHydden** [comment]
Adding both options is fine but please don't remove AMOLED true black.

**Comment by BayLee4** [comment]
Having an option only allowing to chose between Dark/AMOLED (no fully fledged themes) shouldn't be a problem to maintain, but I'm no Android dev and don't know how to do it. I'm closing this PR then.

**Comment by BayLee4** [comment]
Fair enough, it just seems that a substantial amount of people actually care about AMOLEDn removing it does not look like the best option then

**Comment by valldrac** [comment]
I agree we need a 3rd theme instead of deprecating th currente true-dark theme. I'm going to close this PR and request for help in the linked issue. Thank you, @BayLee4, for raising this.

**Pull request closed without merging**
